### ISSUE TITLE
A test randomly failing when compiling the Core

### ISSUE THREAD

**Issue by amarsico** [fp7-netide/Engine#100] opened 2016-06-10 12:00 UTC
Hi @schwabe,
When I compile the Core it sometime happens this error:

```
testMultipleFlowMods(eu.netide.core.caos.test.ScenariosTest)  Time elapsed: 0.024 sec  <<< FAILURE!
java.lang.AssertionError: expected [MyOwnMockSwitch] but found [EuqallyFakeFirewall]
    at org.testng.Assert.fail(Assert.java:94)
    at org.testng.Assert.failNotEquals(Assert.java:496)
    at org.testng.Assert.assertEquals(Assert.java:125)
    at org.testng.Assert.assertEquals(Assert.java:178)
    at org.testng.Assert.assertEquals(Assert.java:188)
    at eu.netide.core.caos.test.ScenariosTest.extractXidFromFirstMsgToBackend(ScenariosTest.java:75)
    at eu.netide.core.caos.test.ScenariosTest.testMultipleFlowMods(ScenariosTest.java:101)


Results :

Failed tests: 
  ScenariosTest.testMultipleFlowMods:101->extractXidFromFirstMsgToBackend:75 expected [MyOwnMockSwitch] but found [EuqallyFakeFirewall]
```

If you recompile, it sometime resolve the issue.

**Comment by KevinPhemius** [comment] 2016-06-10 14:31
Hi @amarsico, 

this is a known bug. As you said recompiling solve the issue.

Best,

---

Kévin

**Comment by schwabe** [comment] 2016-06-23 11:22
Duplicate of #92

**Closed as completed by schwabe** 2016-06-23 11:22 UTC
Labels: Core
