### ISSUE TITLE
FL / Ryu connection

### ISSUE THREAD

**Issue by KevinPhemius** [fp7-netide/Engine#63] opened 2016-01-26 10:15 UTC
Hi,

I tried to test the FL backend v1.2 with the Ryu-shim and the python Core.
The Ryu-shim prints that a "not supported client" tries to connect (but sends the messages correctly) while the backend fails to parse the incoming messages.

Aren't the two of them using the same NetIDE protocol?

Best,
@kjrrp 

P.S: I can't test the FL backend with the ODL shim because I don't have the resources to run it on my machine (I'm traveling with a low perf. laptop).

**Comment by peppepetra** [comment] 2016-01-26 16:17
What Python core are you using?
The backend doesn't support the full NetIDE protocol. It doesn't send ModuleAnnouncement messages, it sends just an HelloMessage to the Core on startup and then just sends OpenFlowMessages from Controller to the core and from Core to the Controller using module ID -1. For that reason it has been tested only with the ProxyCore.

**Comment by KevinPhemius** [comment] 2016-01-26 18:20
I'm using the latest python corefrom the SVN  repo.

<pre>
\netide\Playground\ZeroMQ\ProxyCore.py
</pre>

**Comment by ElisaRojas** [comment] 2016-01-27 10:01
Hi @KevinPhemius , as far as I know, the most current version of the Python core is in the tests folder of the ryu-backend project and I guess you should use that one. At least that is the one that I used for all my tests and it worked for me (and it's called "AdvancedProxyCore", which might mean it's something else :) )

**Comment by peppepetra** [comment] 2016-01-28 09:17
The problem is that Floodlight follows strictly the Openflow protocol. When you had a new switch to the controller, it starts to send to the switch a lot of requests for GetFeature, GetConfig, GetPortDesc etc. If the controller doesn't receive a reply for each of these requests it disconnects the switch. At the moment I am not able to receive all the replies that FL requires from the Ryu Shim. We will work with @doriguzzi to fix the integration during the Madrid meeting. Currently the FL backend, that is in an early stage, can be used only with the ODL Shim. Sorry for the inconvenience.

**Comment by ElisaRojas** [comment] 2016-02-26 23:48
Ok, so this is working ok right now for me, following the Readme.md that @peppepetra updated today. @KevinPhemius , take a look if you want at the code now, but I think we could close the issue.

**Closed as completed** 2016-03-08 12:01 UTC
Labels: question, NetIP, floodlight
